# Generated by Django 5.2.13 on 2026-05-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('acibadem_main', 'Acıbadem main site'), ('bologna_obs', 'OBS Bologna (public)')], db_index=True, max_length=32)),
                ('source_url', models.URLField(help_text='Canonical public URL; duplicates are rejected at the database level.', max_length=2048, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('content_text', models.TextField(help_text='Plain text with HTML removed and normalized whitespace.')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['source', '-updated_at'], name='chat_univer_source_a96cda_idx')],
            },
        ),
    ]
