# Generated by Django 5.2.13 on 2026-05-05 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_chat_history'),
        ('chat', '0003_universitycontent_raw_text'),
    ]

    operations = [
    ]
