# Generated by Django 5.2.13 on 2026-05-05 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_merge_20260505_0558'),
        ('chat', '0004_merge_raw_text_and_chat_history'),
    ]

    operations = [
    ]
