# Generated by Django 5.2.13 on 2026-05-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_merge_20260505_0415'),
        ('chat', '0004_merge_20260505_0558'),
    ]

    operations = [
    ]
