# Generated by Django 5.2.13 on 2026-05-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_merge_20260505_0630'),
        ('chat', '0005_merge_20260505_0700'),
    ]

    operations = [
    ]
