# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_merge_20260505_0700"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_pattern", models.CharField(help_text="Kullanıcı sorusunda aranacak anahtar kelime veya ifade (büyük/küçük harf duyarsız, alt dize).", max_length=512)),
                ("manual_answer", models.TextField(help_text="Eşleşmede döndürülecek kesin cevap.")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
