# Generated by Django 5.2.13 on 2026-05-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_manualresponse'),
        ('chat', '0006_merge_20260505_0715'),
    ]

    operations = [
    ]
